local opt = vim.opt

opt.termguicolors = true
opt.background = "dark"
opt.errorbells = false
opt.smartcase = true
opt.ignorecase = true
opt.showmode = false
opt.swapfile = false
opt.backup = false
opt.undodir = vim.fn.stdpath("config") .. "/undodir"
opt.undofile = true
opt.incsearch = true
opt.hidden = true
opt.completeopt = "menuone,noinsert,noselect"
opt.autoindent = true
opt.smartindent = true
opt.tabstop = 2
opt.softtabstop = 2
opt.shiftwidth = 2
opt.expandtab = true
opt.number = true
opt.relativenumber = true
opt.signcolumn = "yes"
opt.wrap = false
opt.scrolloff = 8
opt.updatetime = 250
opt.splitright = true
opt.splitbelow = true
