[tools]
aws-cli = "latest"
bun = "latest"
"cargo:lumen" = "latest"
"cargo:mdcat" = "latest"
fzf = "latest"
"github:BurntSushi/ripgrep" = "latest"
"github:cli/cli" = "latest"
"github:dandavison/delta" = "latest"
"github:macos-fuse-t/fuse-t" = "latest"
"github:neovim/neovim" = "0.11.6"
"github:rclone/rclone" = "latest"
"github:sharkdp/bat" = "latest"
"github:zellij-org/zellij" = "latest"
"github:tigrisdata/tigrisfs" = "latest"
node = "lts"
starship = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:clawdbot" = "latest"
