return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = "BufReadPost",
  opts = {
    ensure_installed = {
      "bash",
      "c_sharp",
      "comment",
      "css",
      "dockerfile",
      "graphql",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "regex",
      "scss",
      "svelte",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
    highlight = {
      enable = true,
    },
  },
  main = "nvim-treesitter",
}
